version: '3.9'
services:
    torrserver:
        image: asudarchikov/torrserver
        container_name: torrserver
        restart: unless-stopped
        ports:
            - 8090:8090
    jackett:
      image: lscr.io/linuxserver/jackett:latest
      container_name: jackett
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Moscow
          #- RUN_OPTS=<run options here> #optional
      volumes:
        - ./config:/config
        - ./downloads:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped